### ISSUE TITLE
Query bar expands automatically

### ISSUE THREAD

**Issue by SRyan2005** [SRyan2005/EncryptWeb#5]
An additional feature could be the query bar dynamically expands depending on number of lines taken.
Default when it is empty should be 3 lines.

**Comment by aarushpancholi** [comment]
done.

**Comment by SRyan2005** [comment]
If possible could you have the height as 3 lines even when entering the query.

**Comment by aarushpancholi** [comment]
done.

**Comment by SRyan2005** [comment]
Dude it still doesnt work. Try entering multiple letters. It shrinks the bar for some reason.

**Comment by SRyan2005** [comment]
Please only close the issue once I confirm it works!

**Comment by aarushpancholi** [comment]
you can check now and tell me if there is any problem.

**Comment by SRyan2005** [comment]
When filling in the query, the bar shrinks by one line. I feel there is some form of miscommunication so I'll elucidate the specifics.

- The Query Bar should always have a minimum height of three lines (including the spaces between lines of course).
--- ^ Properly test this by adding lots of characters or new lines and removing them to ensure that nothing breaks. I am assuming you have a localhost of the website so make use of that please.^
- No scroll bar should appear to the side (and there shouldn't be any reason to scroll within the query bar besides of course the entire page).
- If the query bar length exceeds 250 characters, display a message in red saying "Too many characters" to the right of the heading "Your Query" in the Berlin Regular Font
- When submitting, instead of redirecting to getform, just display either a pop up or a green message below the button saying "Your Query has been submitted. We will get back to you when possible"

**Comment by SRyan2005** [comment]
Actually, instead of bullet point 3, the query bar shouldn't allow more than 250 characters. If 250 is reached, display "Max Character Length reached" in the aforementioned font and prevent any additional characters from appearing.

**Comment by SRyan2005** [comment]
I know this might feel like nitpicking but I honestly feel this should not have taken this long to fix.

**Comment by aarushpancholi** [comment]
when i was testing the code, the query bar was not shrinking on my side but i'll try to check again and fix it and add the changes you mentioned.

**Comment by SRyan2005** [comment]
So I just did a check on the query bar and it no longer expands. But great job on implementing the word limit feature. Perhaps you could add reasonable limits for the other fields too?
Also please properly word your commits as it'll be nice to know what exactly was changed
